"""empty message

Revision ID: 0376b7f560c9
Revises: 
Create Date: 2023-02-24 08:10:10.022186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0376b7f560c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_shelf')
    op.drop_table('_alembic_tmp_library')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_library',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('creator', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('object', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], name='fk_library_creator_user'),
    sa.PrimaryKeyConstraint('id', name='pk_library')
    )
    op.create_table('_alembic_tmp_shelf',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('block_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], name='fk_shelf_block_id_block'),
    sa.PrimaryKeyConstraint('id', name='pk_shelf')
    )
    # ### end Alembic commands ###
