"""empty message

Revision ID: 564bb231cdd0
Revises: 804b1fc1c22f
Create Date: 2023-07-14 16:22:40.705431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564bb231cdd0'
down_revision = '804b1fc1c22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_shelf', sa.String(length=36), nullable=True))

    with op.batch_alter_table('shelf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_book', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelf', schema=None) as batch_op:
        batch_op.drop_column('active_book')

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_column('active_shelf')

    # ### end Alembic commands ###
