"""empty message

Revision ID: 804b1fc1c22f
Revises: ba246996182b
Create Date: 2023-07-07 11:22:32.276325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804b1fc1c22f'
down_revision = 'ba246996182b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_book', sa.String(length=100), nullable=True))
        batch_op.drop_column('active_chapter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_chapter', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('active_book')

    # ### end Alembic commands ###
