"""empty message

Revision ID: 80eb97ca4085
Revises: 96b85f6e5201
Create Date: 2023-04-16 12:51:55.318596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80eb97ca4085'
down_revision = '96b85f6e5201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_chapter', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active_chapter')

    # ### end Alembic commands ###
