"""empty message

Revision ID: 96b85f6e5201
Revises: 0376b7f560c9
Create Date: 2023-03-04 09:38:17.467678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b85f6e5201'
down_revision = '0376b7f560c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(length=36),
               existing_nullable=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(length=36),
               existing_nullable=False)

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(length=36),
               existing_nullable=False)

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(length=36),
               existing_nullable=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(length=36),
               existing_nullable=False)

    with op.batch_alter_table('shelf', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(length=36),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Text(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('shelf', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Text(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Text(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Text(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Text(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Text(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Text(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
